name: Tag and publish
on:
  push:
    branches:
      - ci-11-publish-schemas

jobs:
  publish_models:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_DATA_SCHEMA_MODELS_ROLE: ${{ secrets.AWS_DATA_SCHEMA_MODELS_ROLE_DEV }}
      DB_NAME: ${{ vars.DB_NAME_DEV }}
      READWRITE_SECRET: ${{ vars.READWRITE_SECRET_DEV }}
      DOCDB_SSH_TUNNEL_SECRET: ${{ vars.DOCDB_SSH_TUNNEL_SECRET_DEV }}
      AWS_DEFAULT_REGION : ${{ vars.AWS_REGION_DEV }}
    steps:
      - uses: actions/checkout@master
      - name: Pull latest changes
        run: git pull origin main
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_DATA_SCHEMA_MODELS_ROLE }}
          role-session-name: github-schema-upload-session
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Create and upload schemas
        run: | 
          python -m pip install -e .
          python -m pip install aind-data-access-api==0.11.0
          python aind_data_schema_models.utils.write_to_docdb.py
